#!/bin/bash

adduser prometheus

cd /home/prometheus
curl -LO "https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz"
tar -xvzf node_exporter-0.16.0.linux-amd64.tar.gz
mv node_exporter-0.16.0.linux-amd64 node_exporter
cd node_exporter
chown prometheus:prometheus node_exporter


#Create a SERVICE /etc/systemd/system/node_exporter.service:
cat << EOF >  /etc/systemd/system/node_exporter.service
[Unit]
Description=Node Exporter

[Service]
User=prometheus
ExecStart=/home/prometheus/node_exporter/node_exporter

[Install]
WantedBy=default.target
EOF


#Reload systemd:
systemctl daemon-reload

#Enable the node_exporter service:
systemctl enable node_exporter.service

#Start the node_exporter service:
systemctl start node_exporter.service



#END




# Container CPU load average:
container_cpu_load_average_10s


# Memory usage query:
((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes) - sum(node_memory_Buffers_bytes) - sum(node_memory_Cached_bytes)) / sum(node_memory_MemTotal_bytes)) * 100
